export const cheatSheetData = {
  cameraShots: [
    { zh: '特写（大特写）', en: 'extreme close-up (ECU)', desc: '眼睛、手部、小细节填满画面' },
    { zh: '特写', en: 'close-up (CU)', desc: '面部或单个物体，紧凑构图' },
    { zh: '近景', en: 'medium close-up (MCU)', desc: '头肩景' },
    { zh: '中景', en: 'medium shot (MS)', desc: '腰部以上' },
    { zh: '中全景', en: 'medium full shot', desc: '膝盖以上' },
    { zh: '全景', en: 'full shot (FS)', desc: '全身，头到脚' },
    { zh: '远景', en: 'wide shot (WS)', desc: '主体加大量环境' },
    { zh: '大远景', en: 'extreme wide shot (EWS)', desc: '广阔景观，主体很小' },
    { zh: '双人镜头', en: 'two-shot', desc: '两个主体同框' },
    { zh: '过肩镜头', en: 'over-the-shoulder (OTS)', desc: '一个主体背后看另一个' },
    { zh: '主观视角', en: 'POV shot', desc: '镜头充当角色的眼睛' },
  ],
  cameraMoves: [
    { zh: '推近', en: 'push-in', desc: '镜头向主体推近（制造紧张/聚焦）' },
    { zh: '拉远', en: 'pull-back / pullout', desc: '镜头远离主体（展示规模）' },
    { zh: '轨道移动', en: 'dolly', desc: '轨道上平滑的横向或前后跟踪' },
    { zh: '横移', en: 'truck left/right', desc: '镜头水平滑动' },
    { zh: '水平摇', en: 'pan left/right', desc: '镜头在轴上水平旋转' },
    { zh: '垂直摇', en: 'tilt up/down', desc: '镜头在轴上垂直旋转' },
    { zh: '升降', en: 'crane up/down', desc: '镜头垂直升降' },
    { zh: '环绕', en: 'orbit / arc', desc: '镜头围绕主体环绕' },
    { zh: '跟拍', en: 'follow shot / tracking shot', desc: '镜头跟随运动主体' },
    { zh: '手持', en: 'handheld', desc: '轻微有机晃动，纪实感' },
    { zh: '斯坦尼康', en: 'Steadicam', desc: '空间中平滑浮动的运动' },
    { zh: '甩镜', en: 'whip pan', desc: '极快水平旋转（转场装置）' },
    { zh: '变焦', en: 'zoom in/out', desc: '镜头焦距变化（非物理移动）' },
  ],
  cameraAngles: [
    { zh: '平视', en: 'eye-level', desc: '中性、自然视角' },
    { zh: '仰拍', en: 'low angle', desc: '镜头仰视主体（力量、英雄感）' },
    { zh: '俯拍', en: 'high angle', desc: '镜头俯视主体（脆弱感）' },
    { zh: '鸟瞰', en: 'bird’s eye / top-down', desc: '正上方垂直俯瞰' },
    { zh: '倾斜构图', en: 'dutch angle / tilted', desc: '镜头在轴上倾斜（不安、紧张）' },
    { zh: '虫眼视角', en: 'worm’s eye', desc: '极低位，地面仰视' },
  ],
  focusDepth: [
    { zh: '浅景深', en: 'shallow depth of field', desc: '背景模糊，主体隔离' },
    { zh: '深焦', en: 'deep focus', desc: '全部清晰对焦，分层构图' },
    { zh: '焦点转移', en: 'rack focus', desc: '焦点从前景转到背景（或反向）' },
    { zh: '分屈光镜', en: 'split diopter', desc: '两个平面同时对焦' },
    { zh: '散景', en: 'bokeh', desc: '柔和的圆形背景虚化高光' },
  ],
  transitions: [
    { zh: '硬切', en: 'cut', desc: '镜头间瞬间切换' },
    { zh: '溶解/交叉淡化', en: 'dissolve / crossfade', desc: '两个镜头渐变融合' },
    { zh: '划接', en: 'wipe', desc: '一个镜头滑过另一个' },
    { zh: '匹配剪辑', en: 'match cut', desc: '在相似形状或运动间切换' },
    { zh: '硬切对比', en: 'smash cut', desc: '突然切换制造冲击或对比' },
    { zh: '淡入/淡出', en: 'fade to black / white', desc: '渐变到纯色' },
    { zh: '甩镜转场', en: 'whip transition', desc: '快速摇镜桥接两个场景' },
  ],
  rhythm: [
    { zh: '慢动作', en: 'slow motion / slow-mo', desc: '降低回放速度增强戏剧性' },
    { zh: '延时摄影', en: 'time-lapse', desc: '压缩时间，云/人群快速移动' },
    { zh: '变速', en: 'speed ramp', desc: '一个镜头内从慢到快（或反向）过渡' },
    { zh: '定格', en: 'freeze frame', desc: '单帧定格为静态画面' },
    { zh: '快切', en: 'quick cuts', desc: '快速镜头切换增加活力' },
    { zh: '长镜头', en: 'long take', desc: '无剪辑的长镜头' },
  ],
  lighting: [
    { zh: '主光', en: 'key light', desc: '主光源，定义氛围' },
    { zh: '轮廓光/背光', en: 'rim light / backlight', desc: '边缘光，将主体从背景中分离' },
    { zh: '补光', en: 'fill light', desc: '柔化主光的阴影' },
    { zh: '英雄光', en: 'hero lighting', desc: '戏剧化的产品广告式灯光' },
    { zh: '体积光', en: 'volumetric light', desc: '可见的光线穿过大气（丁达尔效应/上帝之光）' },
    { zh: '霓虹光', en: 'neon lighting', desc: '彩色人工灯光，赛博朋克美学' },
    { zh: '黄金时刻', en: 'golden hour', desc: '温暖的低角度自然阳光' },
    { zh: '蓝色时刻', en: 'blue hour', desc: '冷色调黄昏环境光' },
    { zh: '钨丝暖光', en: 'tungsten warm', desc: '室内橙暖色调实景灯光' },
    { zh: '明暗对比', en: 'chiaroscuro', desc: '明暗之间的高对比度' },
  ],
  colorPalette: [
    { zh: '暖色调', en: 'warm palette', desc: '红、橙、金（能量、激情、温馨）' },
    { zh: '冷色调', en: 'cool palette', desc: '蓝、银、青（冷静、科技、忧郁）' },
    { zh: '低饱和', en: 'desaturated / muted', desc: '低饱和度，写实或凄凉感' },
    { zh: '高饱和', en: 'high saturation / vibrant', desc: '鲜艳色彩，用于动画、奇幻、广告' },
    { zh: '单色', en: 'monochromatic', desc: '单一色调的层次变化' },
    { zh: '互补对比', en: 'complementary split', desc: '两种对比色（如青橙对比）' },
    { zh: '粉彩', en: 'pastel', desc: '柔和淡色调，温柔或奇幻感' },
  ],
  artStyle: [
    { zh: '照片写实', en: 'photorealistic', desc: '与真实画面无法区分' },
    { zh: '赛璐珞/卡通', en: 'cel-shading / toon', desc: '扁平色彩 + 硬边轮廓' },
    { zh: '水彩', en: 'watercolor', desc: '柔和晕染、纸张纹理、有机边缘' },
    { zh: '水墨', en: 'ink-wash / sumi-e', desc: '中国/日本水墨画美学' },
    { zh: '3D CG 渲染', en: '3D CGI render', desc: '干净 CG，精确材质和光照' },
    { zh: '定格动画', en: 'stop-motion', desc: '逐帧拍摄的实物动画感' },
    { zh: '像素风', en: 'pixel art', desc: '复古低分辨率像素美学' },
    { zh: '油画', en: 'oil painting', desc: '厚重纹理、可见笔触' },
    { zh: '日式动画', en: 'anime', desc: '日式动画风格，表情丰富' },
    { zh: '混合媒介', en: 'mixed media', desc: '一件作品中组合多种视觉风格' },
  ],
  filmGrain: [
    { zh: '35mm 胶片颗粒', en: '35mm film grain', desc: '有机纹理，经典电影感' },
    { zh: '16mm 胶片颗粒', en: '16mm film grain', desc: '更重的颗粒，独立/复古风' },
    { zh: '干净数字', en: 'clean digital', desc: '无颗粒，锐利的现代质感' },
    { zh: 'VHS / 模拟', en: 'VHS / analog', desc: '扫描线、色彩溢出、复古失真' },
    { zh: 'IMAX 清晰度', en: 'IMAX clarity', desc: '超锐利、大画幅电影级细节' },
  ]
};
